version: '3'
services:
  xray-webapp:
    build: .
    image: jaeminlee1996/wrist-scoring:latest
    ports:
      - "5000:5000"
    volumes:
      - ./Pilot_wrist_0615/Test:/app/Pilot_wrist_0615/Test
    restart: unless-stopped 